version: "3"

services:
  app:
    build:
      args:
        user: maksim
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: app-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app

  nginx:
    image: nginx:latest
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - app

networks:
  app:
    driver: bridge